"""empty message

Revision ID: 3c72ba5a8556
Revises: f60dd693f70c
Create Date: 2021-04-23 01:20:24.078101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c72ba5a8556'
down_revision = 'f60dd693f70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_user', 'name')
    # ### end Alembic commands ###
