"""empty message

Revision ID: f60dd693f70c
Revises: eb8dd6d64fab
Create Date: 2021-04-23 00:44:05.718161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f60dd693f70c'
down_revision = 'eb8dd6d64fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('make', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=80), nullable=True),
    sa.Column('year', sa.String(length=255), nullable=True),
    sa.Column('transmission', sa.String(length=255), nullable=True),
    sa.Column('car_type', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('photo', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo'),
    sa.UniqueConstraint('transmission')
    )
    op.create_table('t_favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.String(length=255), nullable=True),
    sa.Column('photo', sa.String(length=80), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('photo'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user')
    op.drop_table('favourites')
    op.drop_table('cars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('make', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('year', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('transmission', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('car_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cars_pkey'),
    sa.UniqueConstraint('photo', name='cars_photo_key'),
    sa.UniqueConstraint('transmission', name='cars_transmission_key')
    )
    op.create_table('favourites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('car_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='favourites_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('biography', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('photo', name='user_photo_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('t_user')
    op.drop_table('t_favourites')
    op.drop_table('t_cars')
    # ### end Alembic commands ###
